/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FORMULARIOS;

/**
 *
 * @author termi
 */
public class frmPRINCIPAL extends javax.swing.JFrame {

    /**
     * Creates new form FRMPRINCIPAL
     */
    public frmPRINCIPAL() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLBcrearUsuario = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JLBverEmpleado = new javax.swing.JLabel();
        JLBcrearPlanilla = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JLBexit = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("MENU PRINCIPAL"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JLBcrearUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBcrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_add_user_male_96px.png"))); // NOI18N
        JLBcrearUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        JLBcrearUsuario.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JLBcrearUsuarioMouseMoved(evt);
            }
        });
        JLBcrearUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLBcrearUsuarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLBcrearUsuarioMouseExited(evt);
            }
        });
        jPanel1.add(JLBcrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 140, 120));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 233, 222));
        jLabel3.setText("Crear Usuario");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, -1));

        JLBverEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBverEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_find_user_male_96px.png"))); // NOI18N
        JLBverEmpleado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JLBverEmpleadoMouseMoved(evt);
            }
        });
        JLBverEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLBverEmpleadoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLBverEmpleadoMouseExited(evt);
            }
        });
        jPanel1.add(JLBverEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 140, 120));

        JLBcrearPlanilla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLBcrearPlanilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_insert_table_96px_9.png"))); // NOI18N
        JLBcrearPlanilla.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JLBcrearPlanillaMouseMoved(evt);
            }
        });
        JLBcrearPlanilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLBcrearPlanillaMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLBcrearPlanillaMouseExited(evt);
            }
        });
        jPanel1.add(JLBcrearPlanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 130, 120));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 255, 255));
        jLabel5.setText("Ver Empleado");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 153));
        jLabel6.setText("Crear Planilla");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 340, 110, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_user_150px_2.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 160, 140));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("Mike ");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 80, 250, 40));

        JLBexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/icons8_Close_40px_2.png"))); // NOI18N
        JLBexit.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                JLBexitMouseMoved(evt);
            }
        });
        JLBexit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JLBexitMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                JLBexitMouseExited(evt);
            }
        });
        jPanel1.add(JLBexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 0, 40, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGENES/fondo-color-verde-azul-neon-claro-fondo-degradado-borroso-abstracto-plantilla-banner_335640-3440 (1).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, -4, 790, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JLBcrearUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLBcrearUsuarioMouseClicked
 
       
        
        
         //AQUI PROGRAMAS MIKExd
           
           
           
         
         
           
        
    }//GEN-LAST:event_JLBcrearUsuarioMouseClicked

    private void JLBcrearUsuarioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLBcrearUsuarioMouseMoved
 
        JLBcrearUsuario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        
    }//GEN-LAST:event_JLBcrearUsuarioMouseMoved

    private void JLBcrearUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLBcrearUsuarioMouseExited
      
         JLBcrearUsuario.setBorder(null);
   
         
    }//GEN-LAST:event_JLBcrearUsuarioMouseExited

    private void JLBverEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLBverEmpleadoMouseClicked
      
       
        //AQUI PROGRAMAS MIKE
           
           
           
           
           
           
           
        
    }//GEN-LAST:event_JLBverEmpleadoMouseClicked

    private void JLBverEmpleadoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLBverEmpleadoMouseMoved
      
        JLBverEmpleado.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        
        
        
    }//GEN-LAST:event_JLBverEmpleadoMouseMoved

    private void JLBverEmpleadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLBverEmpleadoMouseExited

        JLBverEmpleado.setBorder(null);                                                     
  
    }//GEN-LAST:event_JLBverEmpleadoMouseExited

    private void JLBcrearPlanillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLBcrearPlanillaMouseClicked

     
     frmCrearPlanilla F = new frmCrearPlanilla();
     
     F.setVisible(true);
     dispose();
         //AQUI PROGRAMAS MIKE
           
           
           
         
         
         
        
        
    }//GEN-LAST:event_JLBcrearPlanillaMouseClicked

    private void JLBcrearPlanillaMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLBcrearPlanillaMouseMoved
 
           JLBcrearPlanilla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        
   
    }//GEN-LAST:event_JLBcrearPlanillaMouseMoved

    private void JLBcrearPlanillaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLBcrearPlanillaMouseExited

            JLBcrearPlanilla.setBorder(null);
          
    }//GEN-LAST:event_JLBcrearPlanillaMouseExited

    private void JLBexitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLBexitMouseClicked

      System.exit(0);




    }//GEN-LAST:event_JLBexitMouseClicked

    private void JLBexitMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLBexitMouseMoved
 
         JLBexit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        
        
        
        
    }//GEN-LAST:event_JLBexitMouseMoved

    private void JLBexitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JLBexitMouseExited

        
         JLBexit.setBorder(null);
        
        
    }//GEN-LAST:event_JLBexitMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLBcrearPlanilla;
    private javax.swing.JLabel JLBcrearUsuario;
    private javax.swing.JLabel JLBexit;
    private javax.swing.JLabel JLBverEmpleado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
